### ISSUE TITLE
Missing config/mumps_lat_longs.tsv

### ISSUE THREAD

**Issue by jstoja** [nextstrain/mumps#3]
**Current Behavior**  
TravisCI build is failing because of missing file (https://travis-ci.com/nextstrain/mumps/builds/144823906)
The build fails also locally.

**Expected behavior**  
The file `config/mumps_lat_longs.tsv` should be added to the repository in order to make the build succeed.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. `git clone https://github.com/nextstrain/mumps`
2. `nextstrain build mumps/`
4. See error:
```
Building DAG of jobs...
MissingInputException in line 251 of /nextstrain/build/Snakefile:
Missing input files for rule export:
config/mumps_lat_longs.tsv

```

**Your environment: if running Nextstrain locally**  
 - Operating system:  MacOS 10.15.3
 - Version (e.g. `auspice 2.7.0`):  `cli g8c72b6b` and `mumps a760a3c`

This is blocking the test of https://github.com/nextstrain/docker-base/pull/21

**Comment by jstoja** [comment]
@lmoncla It seems that the builds are not working anymore after the addition of this commit (https://github.com/nextstrain/mumps/commit/b0d6728020e01fd1b5cea8c1bfb6df1bd71d66d0).
You're probably the best person to notify about this missing file.

Would you be able to add it to the repository to fix the build?

Thanks!

**Comment by lmoncla** [comment]
I've just uploaded a lat longs file, so this should be fixed. Thanks for the notification!
