### ISSUE TITLE
Other missing files (configs)

### ISSUE THREAD

**Issue by jstoja** [nextstrain/mumps#4]
**Current Behavior**  
TravisCI build is failing because of missing file (https://travis-ci.com/github/nextstrain/mumps/builds/159478986)
The build fails also locally.

**Expected behavior**  
Master build should succeed.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. `git clone https://github.com/nextstrain/mumps`
2. `nextstrain build mumps/`
3. See errors

**Possible solution**  
Upload to this repository the following files:

```
config/include_strains_na_tree.txt
config/dropped_strains_na_tree.txt
config/auspice_config_v1_na.json
config/auspice_config_v1_global.json
```

Your environment: if running Nextstrain locally

    Operating system: MacOS 10.15.3
    Version (e.g. auspice 2.7.0): cli g8c72b6b and bff7ba0

This is blocking the test of nextstrain/docker-base#21

cc @lmoncla That probably knows about those (see #3).

**Comment by lmoncla** [comment]
I've added those files and tested it, and running with both the docker image and local installation should work now.
